In [1]:
import ivy

In [2]:
ivy.set_backend('torch')

ivy.experimental.lu(ivy.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float32'))

(ivy.array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 ivy.array([[1.        , 0.        , 0.        ],
        [0.1429    , 1.        , 0.        ],
        [0.57139999, 0.5       , 1.        ]]),
 ivy.array([[7.        , 8.        , 9.        ],
        [0.        , 0.85710001, 1.71430004],
        [0.        , 0.        , 0.        ]]))

In [3]:
ivy.set_backend('numpy')
ivy.experimental.lu(ivy.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float32'))

(ivy.array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 ivy.array([[1.    , 0.    , 0.    ],
        [0.1429, 1.    , 0.    ],
        [0.5714, 0.5   , 1.    ]]),
 ivy.array([[7.        , 8.        , 9.        ],
        [0.        , 0.85710001, 1.71430004],
        [0.        , 0.        , 0.        ]]))

In [7]:
# ivy.set_backend('tensorflow')
# ivy.experimental.lu(ivy.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float32'))

In [41]:
import tensorflow as tf
from typing import Optional, Tuple
def lu(
    x: tf.Tensor,
    /,
    *,
    pivot: Optional[bool] = True,
) -> Tuple[tf.Tensor, tf.Tensor, tf.Tensor]:
    n = x.shape[0]
    L = tf.eye(n)
    U = tf.identity(x)
    P = tf.eye(n)

    for k in range(n - 1):
        if pivot:
            # partial pivoting
            max_idx = tf.math.argmax(tf.abs(U[k:, k]))+ k
            print(max_idx)
            # U[[k, max_idx]] = U[[max_idx, k]]
            # swap rows of U
            # perform row swapping operation
            U = tf.tensor_scatter_nd_update(U, [[k], [max_idx]], tf.gather(U, [max_idx, k]))
            # U = tf.tensor_scatter_nd_update(U, [[k], [max_idx]], tf.gather(U, [max_idx, k]), [k, k])
            print(U)
            if k > 0:
                L[[k, max_idx], :k] = L[[max_idx, k], :k]
            print(L)
            if max_idx != k:
                P = tf.tensor_scatter_nd_update(P, [[k], [max_idx]], tf.gather(P, [max_idx, k]))
            print(P)
        # elimination
        div = U[k, k]
        L[k + 1 :, k] = U[k + 1 :, k] / div
        U[k + 1 :, k:] -= L[k + 1 :, k, None] * U[k, k:]
        U[k + 1 :, k] = 0.0
    P = tf.round(P, 4)
    L = tf.round(L, 4)
    U = tf.round(U, 4)
    # ROUND P,L,U to 4 dp if more else fine
    return P, L, U


In [42]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr_tensor = tf.convert_to_tensor(arr)
lu(arr_tensor, pivot=True)

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(
[[7 8 9]
 [4 5 6]
 [1 2 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]], shape=(3, 3), dtype=float32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment